<?php 

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_artists',
		'title' => 'Artists',
		'fields' => array (
			array (
				'key' => 'field_55dd27cb61a94',
				'label' => 'Current Tours',
				'name' => 'current_tours',
				'type' => 'post_object',
				'instructions' => '(Optional) Upcoming tour dates',
				'post_type' => array (
					0 => 'event',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 0,
				'multiple' => 1,
			),
			array (
				'key' => 'field_55dd25cada96d',
				'label' => 'Website Link',
				'name' => 'website_link',
				'type' => 'text',
				'instructions' => '(Optional) URL of the artist\'s website',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_55dd26c0da96e',
				'label' => 'Instagram Link',
				'name' => 'instagram_link',
				'type' => 'text',
				'instructions' => '(Optional) Link to artist\'s Instagram profile',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_55dd26e4da96f',
				'label' => 'Twitter Link',
				'name' => 'twitter_link',
				'type' => 'text',
				'instructions' => '(Optional) Link to artist\'s Twitter feed',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_55dd2702da970',
				'label' => 'Facebook Link',
				'name' => 'facebook_link',
				'type' => 'text',
				'instructions' => '(Optional) Link to artist\'s Facebook profile',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_55dd2718da971',
				'label' => 'Soundcloud Link',
				'name' => 'soundcloud_link',
				'type' => 'text',
				'instructions' => '(Optional) Link to artist\'s Soundcloud profile',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_55dd2cd868408',
				'label' => 'Video URL',
				'name' => 'video_url',
				'type' => 'text',
				'instructions' => '(Optional) Vimeo or YouTube video for the artist\'s page',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'artist',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_events',
		'title' => 'Events',
		'fields' => array (
			array (
				'key' => 'field_55dce7f232d18',
				'label' => 'Date',
				'name' => 'date',
				'type' => 'date_picker',
				'instructions' => 'Must be in the future.',
				'required' => 1,
				'date_format' => 'yymmdd',
				'display_format' => 'M dd',
				'first_day' => 1,
			),
			array (
				'key' => 'field_55dd1fe398820',
				'label' => 'Artists',
				'name' => 'artists',
				'type' => 'post_object',
				'instructions' => 'The artists playing or performing the event',
				'required' => 1,
				'post_type' => array (
					0 => 'artist',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 0,
				'multiple' => 1,
			),
			array (
				'key' => 'field_55dd21237b433',
				'label' => 'Type',
				'name' => 'type',
				'type' => 'text',
				'instructions' => 'What type of event is this? Defaults to \'Concert\'',
				'default_value' => 'Concert',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_55dd218e7b434',
				'label' => 'Venue',
				'name' => 'venue',
				'type' => 'text',
				'instructions' => 'The name of the venue where the event is to take place',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_55dd221b4c5ae',
				'label' => 'Location',
				'name' => 'location',
				'type' => 'text',
				'instructions' => 'City and country where the venue is to take place',
				'required' => 1,
				'default_value' => '',
				'placeholder' => 'e.g. Paris, France',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'event',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}
